sudo: required
services:
  - docker

before_install:
  - docker build -t safwenrabelsi/docker-react -f Dockerfile.dev .

script:
  - docker run  -e CI=true safwenrabelsi/docker-react npm run test

deploy:
  provider: elasticbeanstack
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-630363084470"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_id:
    secure: $AWS_SECRET_KEY
